services:
  postgres:
    image: postgres:17.5
    container_name: travel_advisor_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: travel_advisor_flask_app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    volumes:
      - ./data:/travel_assistant/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: travel_advisor_network
